### ISSUE TITLE
Erro download ebook

### ISSUE THREAD

**Issue by Dalvani** [Hai567/Scribd-Downloader#1]
1. Download eBook
2. Download Audio Book
3. Exit
Choose (1/2): 1
Enter The eBook URL You Want To Download: https://pt.scribd.com/read/653655703/Sap-Hana-All-About-Views
Fetching Data...
Traceback (most recent call last):
  File "D:\scribd\main.py", line 279, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\scribd\main.py", line 267, in main
    await eBook()
  File "D:\scribd\main.py", line 142, in eBook
    await page.goto(bookURL.replace('book', 'read'))
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\async_api\_generated.py", line 9251, in goto
    await self._impl_obj.goto(
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_page.py", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_frame.py", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://pt.scribd.com/read/653655703/Sap-Hana-All-About-Views", waiting until "load"
============================================================

I have the error above. Can you help me?

**Comment by Hai567** [comment]
> 1. Download eBook
> 
> 2. Download Audio Book
> 
> 3. Exit
> 
> Choose (1/2): 1
> 
> Enter The eBook URL You Want To Download: https://pt.scribd.com/read/653655703/Sap-Hana-All-About-Views
> 
> Fetching Data...
> 
> Traceback (most recent call last):
> 
>   File "D:\scribd\main.py", line 279, in <module>
> 
>     asyncio.run(main())
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
> 
>     return future.result()
> 
>   File "D:\scribd\main.py", line 267, in main
> 
>     await eBook()
> 
>   File "D:\scribd\main.py", line 142, in eBook
> 
>     await page.goto(bookURL.replace('book', 'read'))
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\async_api\_generated.py", line 9251, in goto
> 
>     await self._impl_obj.goto(
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_page.py", line 473, in goto
> 
>     return await self._main_frame.goto(**locals_to_params(locals()))
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_frame.py", line 138, in goto
> 
>     await self._channel.send("goto", locals_to_params(locals()))
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 61, in send
> 
>     return await self._connection.wrap_api_call(
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
> 
>     return await cb()
> 
>   File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
> 
>     result = next(iter(done)).result()
> 
> playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
> 
> =========================== logs ===========================
> 
> navigating to "https://pt.scribd.com/read/653655703/Sap-Hana-All-About-Views", waiting until "load"
> 
> ============================================================
> 
> 
> 
> I have the error above. Can you help me?

Did you use a premium Scribd Account?
